"""Emit the thermometer encoder and the top-level wrapper from a checkpoint.

The encoder is the piece published DWN resource totals leave out. They exclude the binarization
front end entirely, and Mecik & Kumm measured that omission at up to 3.2x the reported LUTs. On
a large part it may not matter; on a small one it can dominate. In the study's smallest
model the encoder was FOURTEEN TIMES the network it fed -- 50 LUT6 nodes against 202
comparators.

So encoder and core are emitted as SEPARATE modules, wired together by a thin top. That is not
tidiness: it is what makes it possible to synthesize each alone and report their areas
separately, which this tool does unconditionally. See CLAUDE.md, "design invariants".

What gets built:
  thermometer_encoder.v   one comparator per USED thermometer bit, constants folded in
  dwn_top.v               encoder -> core
  dwn_top_params.vh       end-to-end latency

Only the thermometer bits some node actually reads are given a comparator. The rest of the
vector is tied low: no node reads them, so they cost nothing after synthesis, and keeping the
full width means dwn_core does not have to change to match.

Ported from the study's `rtlgen/emit_encoder.py`. Changes: the CLI `main()` became
`build_encoder()`; the dataset lookup that supplied default word/frac widths is gone, and both
are now REQUIRED arguments (see precision.py for where they come from); and two emitted Verilog
comments that hardcoded one model's numbers now carry the actual ones.
"""

import os
import re

import numpy as np

from .extract import quantize_thresholds, fits_in_word


def emit_encoder(ck, used, out_path, frac_bits, word):
    cfg = ck['config']
    z = cfg['thermometer_bits']
    thresholds = ck['thermometer']['thresholds'].numpy()
    n_features, total_bits = thresholds.shape[0], thresholds.size

    thr_q = quantize_thresholds(thresholds, frac_bits)
    if not fits_in_word(thr_q, word):
        # ValueError, not SystemExit: this is a library. SystemExit would take down a caller's
        # process from inside a function it merely imported.
        raise ValueError(
            f'thresholds do not fit in {word}-bit signed at Q{word-1-frac_bits}.{frac_bits}: '
            f'range [{thr_q.min()}, {thr_q.max()}]')

    L = []
    L.append('// GENERATED by dwn2rtl -- do not edit by hand.')
    L.append(f"// run    : {ck.get('run_name', '(unnamed)')}")
    L.append(f'// format : Q{word-1-frac_bits}.{frac_bits} signed, {word}-bit features')
    L.append(f'// scope  : {used.size} comparators for {total_bits} thermometer bits '
             f'({100*used.size/total_bits:.1f}%)')
    L.append('//')
    L.append('// Each comparator is `feature > constant`, with the threshold folded to an')
    L.append('// integer at export time.')
    L.append('//')
    L.append('// WARNING: thresholds live in whatever feature space the model was TRAINED in. If')
    L.append('// that training applied a scaler, whatever drives x_flat must apply the same one,')
    L.append('// with the same fitted parameters, before quantizing. Feeding this module raw')
    L.append('// features when the model saw scaled ones produces a design that runs at chance')
    L.append('// and looks entirely healthy doing it.')
    # Said concretely or not at all. This block previously ended "The checkpoint carries the
    # scaler for this reason" -- true of the checkpoint, and false of what dwn2rtl emitted,
    # which dropped it. A user following that sentence would have found nothing to follow it
    # with. Now the emitted directory either carries the numbers or says there are none.
    if ck.get('scaler') and 'mean' in ck['scaler']:
        L.append('//')
        L.append('// THIS MODEL WAS TRAINED ON SCALED FEATURES. The parameters are emitted')
        L.append('// beside this file as input_scaling.json -- apply (x - mean) / scale before')
        L.append('// quantizing.')
    else:
        L.append('//')
        L.append('// This checkpoint records no scaler, so features arrive in their raw space.')
    L.append('//')
    L.append('// Undriven bits are tied low in the default assignment below. No node reads')
    L.append('// them, so synthesis should remove them entirely; if the LUT count says')
    L.append('// otherwise, that is a finding worth chasing.')
    L.append('')
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('module thermometer_encoder (')
    L.append(f'    input  wire [{n_features*word-1}:0] x_flat,   '
             f'// {n_features} features x {word} bits, feature f at [f*{word} +: {word}]')
    L.append(f'    output reg  [{total_bits-1}:0] bits')
    L.append(');')
    L.append('')
    L.append('    integer i;')
    L.append('')
    L.append('    always @* begin')
    L.append(f'        bits = {total_bits}\'b0;')

    for b in sorted(used.tolist()):
        f_idx, t_idx = divmod(int(b), z)
        t = int(thr_q[f_idx, t_idx])
        L.append(f'        bits[{b:4d}] = $signed(x_flat[{f_idx}*{word} +: {word}]) > '
                 f'$signed({word}\'sd{t});' if t >= 0 else
                 f'        bits[{b:4d}] = $signed(x_flat[{f_idx}*{word} +: {word}]) > '
                 f'-$signed({word}\'sd{-t});')

    L.append('    end')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')
    return thr_q


def emit_top(ck, out_path, total_bits, n_features, num_classes, core_latency,
             word, pipe_enc=1, core_pipe=(1, 1, 1), used_bits=None):
    idx_w = max(1, int(np.ceil(np.log2(num_classes))))
    latency = pipe_enc + core_latency
    core_lut, core_pop, core_out = core_pipe
    L = []
    L.append('// GENERATED by dwn2rtl -- do not edit by hand.')
    L.append('//')
    L.append('// Pipelined: quantized features in, class index out, one result per clock')
    L.append('// (II=1). Latency is PIPE_ENC + the core\'s own stages.')
    L.append('//')
    # These counts are this model's, read from its own wiring. They were literals in the earlier
    # repo -- "202" and "3200" -- which meant every emitted design carried the first model's
    # numbers in its header no matter what it actually was. A comment cannot break a design,
    # but a comment that confidently states someone else's numbers is worse than no comment.
    if used_bits is not None:
        L.append(f'// Only {used_bits} of the encoder\'s {total_bits} output bits feed a node, so the')
        L.append(f'// register below is nominally {total_bits} wide but should synthesize to about')
        L.append(f'// {used_bits} flops -- the rest drive nothing and are expected to be trimmed. If')
        L.append('// the FF count says otherwise, the register is holding dead bits and the')
        L.append('// emitter should narrow it explicitly.')
    L.append('')
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    # These three MUST match what emit_core.py emitted -- dwn_top passes them down and so
    # overrides dwn_core's own defaults. They are read from dwn_core_params.vh, never retyped.
    L.append('module dwn_top #(')
    L.append(f'    parameter integer PIPE_ENC = {pipe_enc},   // after the comparators')
    L.append(f'    parameter integer PIPE_LUT = {core_lut},')
    L.append(f'    parameter integer PIPE_POP = {core_pop},')
    L.append(f'    parameter integer PIPE_OUT = {core_out}')
    L.append(')(')
    L.append('    input  wire clk,')
    L.append(f'    input  wire [{n_features*word-1}:0] x_flat,')
    L.append(f'    output wire [{idx_w-1}:0] class_idx')
    L.append(');')
    L.append('')
    L.append(f'    wire [{total_bits-1}:0] bits;')
    L.append(f'    wire [{total_bits-1}:0] bits_q;')
    L.append('')
    L.append('    thermometer_encoder u_enc (.x_flat(x_flat), .bits(bits));')
    L.append('')
    L.append(f'    pipe_reg #(.WIDTH({total_bits}), .ENABLE(PIPE_ENC)) u_pipe_enc')
    L.append('        (.clk(clk), .d(bits), .q(bits_q));')
    L.append('')
    L.append('    dwn_core #(.PIPE_LUT(PIPE_LUT), .PIPE_POP(PIPE_POP), .PIPE_OUT(PIPE_OUT))')
    L.append('        u_core (.clk(clk), .x(bits_q), .class_idx(class_idx));')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')

    with open(os.path.join(os.path.dirname(out_path), 'dwn_top_params.vh'), 'w') as f:
        f.write('// GENERATED by dwn2rtl -- do not edit.\n')
        f.write(f'`define DWN_TOP_LATENCY {latency}\n')
    return latency


def verify_emitted(path, used, thr_q, z, word):
    """Parse the emitted comparators back and check every one against the checkpoint."""
    src = open(path).read()
    pat = re.compile(
        r'bits\[\s*(\d+)\] = \$signed\(x_flat\[(\d+)\*\d+ \+: \d+\]\) > '
        r'(-?)\$signed\(\d+\'sd(\d+)\);')
    seen = {}
    for m in pat.finditer(src):
        b, f_idx, neg, mag = int(m.group(1)), int(m.group(2)), m.group(3), int(m.group(4))
        seen[b] = (f_idx, -mag if neg else mag)

    assert set(seen) == set(used.tolist()), (
        f'emitted {len(seen)} comparators, expected {used.size}')
    for b, (f_got, t_got) in seen.items():
        f_exp, t_idx = divmod(int(b), z)
        t_exp = int(thr_q[f_exp, t_idx])
        assert f_got == f_exp, f'bit {b}: feature {f_got} != {f_exp}'
        assert t_got == t_exp, f'bit {b}: threshold {t_got} != {t_exp}'
    return len(seen)


def build_encoder(ck, outdir, precision, pipe_enc=1):
    """Emit thermometer_encoder.v + dwn_top.v + dwn_top_params.vh, then read back and check.

    Replaces the study's argparse `main()`. `precision` is a precision.Precision -- there
    is no default and no dataset lookup behind it, because a caller that does not know the word
    width does not know enough to emit an encoder.

    MUST run after build_core(): the core's pipeline depth is read out of dwn_core_params.vh
    rather than passed in a second time, so the two emitters cannot be handed contradicting
    depths and produce a top whose latency constant does not match its own pipeline.
    """
    from .extract import layer_indices, extract_tables, extract_wiring
    from .precision import required_int_bits

    cfg = ck['config']
    n, num_classes, z = cfg['n'], cfg['num_classes'], cfg['thermometer_bits']
    thresholds = ck['thermometer']['thresholds'].numpy()
    n_features, total_bits = thresholds.shape[0], thresholds.size
    word, frac = precision.word_bits, precision.frac_bits

    # Integer width is derivable exactly, so refuse a word that cannot hold the thresholds. A
    # threshold outside the range makes every comparison against it meaningless, and the design
    # would still elaborate and still synthesize. Fractional width is NOT derivable this way --
    # see required_int_bits().
    need = required_int_bits(thresholds)
    if precision.int_bits < need:
        raise ValueError(
            f'{precision} cannot represent this model. Its thresholds span '
            f'+/-{float(np.abs(thresholds).max()):.4g} and need {need} integer bits; this '
            f'format has {precision.int_bits}. Widen the word or use fewer fractional bits.')

    first = layer_indices(ck['state_dict'])[0]
    extract_tables(ck['state_dict'], first)          # shape assertions
    wiring, _ = extract_wiring(ck['state_dict'], first, n)
    used = np.unique(wiring)

    enc_path = os.path.join(outdir, 'thermometer_encoder.v')
    top_path = os.path.join(outdir, 'dwn_top.v')

    core_params = os.path.join(outdir, 'dwn_core_params.vh')
    if not os.path.exists(core_params):
        raise FileNotFoundError(
            f'{core_params} missing -- build_core() must run before build_encoder(), so the '
            'top reads the core\'s real pipeline depth instead of assuming one.')
    params_src = open(core_params).read()
    core_latency = int(re.search(r'`define DWN_CORE_LATENCY (\d+)', params_src).group(1))

    def core_pipe_of(stage, default=1):
        mm = re.search(rf'`define DWN_CORE_PIPE_{stage} (\d+)', params_src)
        return int(mm.group(1)) if mm else default

    core_pipe = (core_pipe_of('LUT'), core_pipe_of('POP'), core_pipe_of('OUT'))

    thr_q = emit_encoder(ck, used, enc_path, frac_bits=frac, word=word)
    latency = emit_top(ck, top_path, total_bits, n_features, num_classes, core_latency,
                       word=word, pipe_enc=pipe_enc, core_pipe=core_pipe,
                       used_bits=int(used.size))

    seen = verify_emitted(enc_path, used, thr_q, z, word=word)

    return {
        'encoder_path': enc_path,
        'top_path': top_path,
        'comparators': int(used.size),
        'comparators_checked': seen,
        'thermometer_bits': int(total_bits),
        'features': int(n_features),
        'precision': precision,
        'threshold_range': (int(thr_q.min()), int(thr_q.max())),
        'core_latency': core_latency,
        'latency': latency,
        'pipe_enc': pipe_enc,
        'core_pipe': core_pipe,
    }
