"""Emit the model-specific DWN core Verilog from a checkpoint, then read it back and check it.

  hand-written   rtl/lut_node.v, popcount.v, argmax.v -- shipped as package data. The structure
                 and the address/tie-break conventions: everything with a decision in it
  emitted        dwn_core.v -- one truth table and n wire indices per node: pure transcription

⚠️ `verify_emitted()` below is NOT the gate. It parses the emitted file back and asserts every
table and wire index against the checkpoint, which catches a wrong constant and -- the reason it
exists -- a reversed address concatenation. But it only proves the file SAYS what the checkpoint
says, never how the Verilog BEHAVES. In the study an emitter's own read-back reported 20/20
correct while the design was wrong on 958 of 1,504 vectors. Only a simulator closes that gap.
"""

import os
import re

import numpy as np

from .extract import layer_indices, extract_tables, extract_wiring

# DEFAULT pipeline depth. `emit()` takes the depths as arguments so a build can vary them
# without editing this file. config.py carries the chosen values; these three are only the
# fallback for a caller that says nothing.
PIPE_LUT = 1
PIPE_POP = 1
PIPE_OUT = 1


MAX_COMMENT = 120


class EmitterMismatch(ValueError):
    """The emitted file does not say what the checkpoint says.

    ⚠️ AN EXCEPTION, NOT AN `assert`, AND THAT IS THE WHOLE POINT. Every read-back check in
    both emitters used to be `assert`, which `python -O` deletes -- so under `-O` a build with
    a reversed address concatenation on disk completed successfully and reported nothing
    (phase8-ledger.md §4). The one check written to catch this project's named worst-case bug
    was removable by a runtime flag nobody thinks about.

    ValueError, so callers that already catch the emitters' bad-input errors keep working, and
    the CLI reports it as a sentence rather than a traceback.
    """


def generated_header(suffix='by hand'):
    """The first line of every emitted file, carrying the version that wrote it.

    ⚠️ Not decoration. The hand-written primitives are copied VERBATIM (build.py copies bytes so
    Windows cannot rewrite their line endings), so they carry no version of their own -- and a
    user who updates the generated files without the primitives gets a parameter mismatch whose
    only symptom is "Parameter not found". Stamping the generated half makes that diagnosable:
    the file states which dwn2rtl wrote it, so a mismatch is visible rather than mysterious.

    It also answers the first question of every bug report.
    """
    from . import __version__          # late, so importing this module cannot cycle
    return f'// GENERATED by dwn2rtl {__version__} -- do not edit {suffix}.'


def comment_safe(value, fallback='(unnamed)'):
    """Anything a checkpoint carries -> one safe line of a Verilog comment.

    ⚠️ run_name and results reach the emitted header and NOTHING else, and all three ways they
    could go wrong produced something worse than a missing comment:

      a newline    escaped the `//` and emitted Verilog that does not compile
      non-ASCII    crashed the build with UnicodeEncodeError when writing the file
      a long value pushed a header line past any sane width

    Metadata must never be able to break a design, so it is flattened, transliterated to ASCII
    and truncated rather than trusted.
    """
    if value is None or value == '':
        return fallback
    text = ' '.join(str(value).split())                      # newlines and tabs -> spaces
    text = text.encode('ascii', 'replace').decode('ascii')   # cp1252 consoles and files
    if len(text) > MAX_COMMENT:
        text = text[:MAX_COMMENT - 3] + '...'
    return text or fallback


def accuracy_line(results, label='accuracy   '):
    """The accuracy header line, for whatever the checkpoint happens to hold there.

    ⚠️ `final_acc` is formatted with :.4f, so a string, None or a list raised TypeError from a
    code generator -- over a comment. Numbers are formatted; anything else is reported as it is.
    """
    results = results or {}
    if 'unrecognized' in results and 'final_acc' not in results:
        # Recorded, but not as anything readable -- which is a different fact from absent.
        return (f'// {label}: the results field is a '
                f'{comment_safe(results["unrecognized"])}, not a mapping; nothing to read')
    if 'final_acc' not in results:
        return f'// {label}: not recorded in the checkpoint'

    def num(v):
        try:
            return f'{float(v):.4f}'
        except (TypeError, ValueError):
            return comment_safe(v, fallback='?')

    best = (results or {}).get('best_acc')
    best_txt = f', {num(best)} best epoch' if best is not None else ''
    return f'// {label}: final {num(results["final_acc"])} (software{best_txt})'

def table_to_hex(row):
    """bool[2**n] -> integer where bit `addr` is row[addr].

    An explicit loop, not np.packbits: packbits pads a partial byte on the low side, so a
    4-entry table emitted as 0x70 instead of 0x07. Only n < 3 was affected, which is why n=6
    never showed it.
    """
    v = 0
    for addr, bit in enumerate(row):
        if bit:
            v |= 1 << addr
    return v


MAX_N = 6      # one LUT6 holds 2**6 entries; see the check in emit()


def emit(ck, out_path, pipe_lut=PIPE_LUT, pipe_pop=PIPE_POP, pipe_out=PIPE_OUT,
         build_id=None):
    cfg = ck['config']
    n, num_classes = cfg['n'], cfg['num_classes']

    # ⚠️ n > 6 overflows the 64-bit TABLE parameter and Verilog truncates it silently. Widening
    # it is not a width change: one node would stop being one LUT6.
    if n > MAX_N:
        raise ValueError(
            f'n={n} exceeds MAX_N={MAX_N}. A {2**n}-entry table does not fit the 64-bit TABLE '
            f'parameter and would be silently truncated. Supporting it requires changing '
            f'rtl/lut_node.v, this emitter and verify_emitted together -- and one node would no '
            f'longer map to one LUT6, which is the premise the whole approach rests on.')
    sd = ck['state_dict']

    layers = []
    for i in layer_indices(sd):
        layers.append((extract_tables(sd, i), *extract_wiring(sd, i, n)))

    # From the thresholds, (features, z), never a literal feature count -- one dataset's count
    # written in here emits a core whose input port silently disagrees with the encoder.
    input_bits = ck['thermometer']['thresholds'].numpy().size
    final_width = layers[-1][0].shape[0]
    group = final_width // num_classes
    score_w = int(np.ceil(np.log2(group + 1)))
    idx_w = max(1, int(np.ceil(np.log2(num_classes))))

    L = []
    L.append(generated_header())
    L.append(f"// run        : {comment_safe(ck.get('run_name'))}")
    L.append(f"// config     : n={n}, layers={cfg['layers']}, z={cfg['thermometer_bits']}, "
             f'classes={num_classes}')
    # Metadata only -- it reaches this comment and nothing else. Absent is reported as absent:
    # defaulting to 0.0 would print "this model scores zero" instead of "nobody wrote it down".
    L.append(accuracy_line(ck.get('results')))
    L.append('//')
    L.append('// Takes the FULL binarized vector, so it can be driven straight from the')
    L.append('// core-level test vectors. Typically most of those bits feed no node at all and')
    L.append('// synthesis is expected to drop them; dwn_top drives only the bits that matter,')
    L.append('// from the thermometer encoder.')
    L.append('')
    # Required: xsim rejects a design mixing modules with and without a timescale, and the
    # testbench declares one.
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('// Pipeline stages are parameters, not hand-placement, so depth can be swept')
    L.append('// without regenerating. Set any to 0 to compile that register out. LATENCY is the')
    L.append('// sum of the enabled stages and is emitted into dwn_core_params.vh for the')
    L.append('// testbench, so the two can never disagree about it.')
    L.append('//')
    L.append('// Placement follows measurement, not intuition: out-of-context synthesis put')
    L.append('// 10.194 ns in this module against 2.962 ns in the encoder, so the depth is in')
    L.append('// the popcount and argmax trees. Hence a stage after each of them.')
    L.append('module dwn_core #(')
    L.append(f'    parameter integer PIPE_LUT = {pipe_lut},   // after each LUT layer')
    L.append(f'    parameter integer PIPE_POP = {pipe_pop},   // after the popcounts')
    L.append(f'    parameter integer PIPE_OUT = {pipe_out}    // after the argmax')
    L.append(')(')
    L.append('    input  wire clk,')
    L.append(f'    input  wire [{input_bits-1}:0] x,')
    L.append(f'    output wire [{idx_w-1}:0]    class_idx')
    L.append(');')
    L.append('')

    prev = 'x'
    for li, (tables, wiring, kind) in enumerate(layers):
        count = tables.shape[0]
        L.append(f'    // ---- layer {li}: {count} nodes, {kind} mapping ----')
        L.append(f'    wire [{count-1}:0] layer{li};')
        for j in range(count):
            # Concatenation is MSB-first, and slot 0 must land on addr[0], so the slots are
            # listed in REVERSE order here. This is the single most reversible-looking
            # decision in the whole design (docs/checkpoint-format.md §2).
            slots = ', '.join(f'{prev}[{b}]' for b in reversed(wiring[j].tolist()))
            L.append(f'    lut_node #(.N({n}), .TABLE(64\'h{table_to_hex(tables[j]):016X}))')
            L.append(f'        u_l{li}_n{j} (.addr({{{slots}}}), .out(layer{li}[{j}]));')
        L.append('')
        L.append(f'    wire [{count-1}:0] layer{li}_q;')
        L.append(f'    pipe_reg #(.WIDTH({count}), .STAGES(PIPE_LUT)) u_pipe_l{li} '
                 f'(.clk(clk), .d(layer{li}), .q(layer{li}_q));')
        L.append('')
        prev = f'layer{li}_q'

    L.append('    // ---- output stage: contiguous per-class popcounts, then argmax ----')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores;')
    for c in range(num_classes):
        lo, hi = c * group, (c + 1) * group - 1
        L.append(f'    popcount #(.WIDTH({group})) u_pc{c} '
                 f'(.bits({prev}[{hi}:{lo}]), .count(scores[{c*score_w+score_w-1}:{c*score_w}]));')
    L.append('')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores_q;')
    L.append(f'    pipe_reg #(.WIDTH({num_classes*score_w}), .STAGES(PIPE_POP)) u_pipe_pop '
             f'(.clk(clk), .d(scores), .q(scores_q));')
    L.append('')
    L.append(f'    wire [{idx_w-1}:0] idx;')
    L.append(f'    argmax #(.K({num_classes}), .W({score_w})) u_argmax '
             f'(.scores_flat(scores_q), .index(idx));')
    L.append('')
    L.append(f'    pipe_reg #(.WIDTH({idx_w}), .STAGES(PIPE_OUT)) u_pipe_out '
             f'(.clk(clk), .d(idx), .q(class_idx));')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')

    # Latency emitted alongside the RTL so the testbench reads it from the same source that
    # generated the pipeline. Hardcoding it in the testbench is how a depth change silently
    # turns into an off-by-one comparison against the wrong vector.
    core_latency = pipe_lut * len(layers) + pipe_pop + pipe_out
    # The individual stage enables go here too, not just their sum. dwn_top instantiates
    # dwn_core with .PIPE_LUT(PIPE_LUT) etc., so dwn_top's OWN defaults override the core's --
    # emitting a 0 here and leaving dwn_top at 1 would silently put the stage back. Publishing
    # them makes emit_encoder read the depth rather than be told it a second time.
    with open(os.path.join(os.path.dirname(out_path), 'dwn_core_params.vh'), 'w') as f:
        f.write(generated_header('this file') + '\n')
        f.write(f'`define DWN_CORE_LATENCY {core_latency}\n')
        f.write(f'`define DWN_CORE_PIPE_LUT {pipe_lut}\n')
        f.write(f'`define DWN_CORE_PIPE_POP {pipe_pop}\n')
        f.write(f'`define DWN_CORE_PIPE_OUT {pipe_out}\n')
        # Ties this file to the vectors written by the same build -- see build.build_id().
        if build_id:
            f.write(f'`define DWN_BUILD_ID "{build_id}"\n')

    return layers, input_bits, group, score_w, core_latency


def verify_emitted(path, layers, n):
    """Parse the emitted Verilog back and check it against the checkpoint.

    Catches a wrong table, a wrong wire index, and -- most importantly -- a reversed address
    concatenation. Cheap, and it fails at emit time rather than in simulation.

    ⚠️ NOT a substitute for the simulator. It proves the file says what the checkpoint says,
    which is a claim about transcription, not about behaviour. See the module docstring.
    """
    src = open(path).read()
    pat = re.compile(
        r"lut_node #\(\.N\(\d+\), \.TABLE\(64'h([0-9A-F]{16})\)\)\s*"
        r"u_l(\d+)_n(\d+) \(\.addr\(\{([^}]*)\}\)",
        re.MULTILINE)

    seen = 0
    for m in pat.finditer(src):
        tbl_hex, li, j = m.group(1), int(m.group(2)), int(m.group(3))
        tables, wiring, _ = layers[li]

        expect_hex = f'{table_to_hex(tables[j]):016X}'
        if tbl_hex != expect_hex:
            raise EmitterMismatch(
                f'layer {li} node {j}: table {tbl_hex} != expected {expect_hex}')

        idx = [int(x) for x in re.findall(r'\[(\d+)\]', m.group(4))]
        # emitted MSB-first, so reversing recovers slot order (slot 0 first)
        if idx[::-1] != wiring[j].tolist():
            raise EmitterMismatch(
                f'layer {li} node {j}: wiring {idx[::-1]} != expected {wiring[j].tolist()} '
                '-- address bit order is wrong')
        seen += 1

    total = sum(t.shape[0] for t, _, _ in layers)
    if seen != total:
        raise EmitterMismatch(f'parsed {seen} nodes, expected {total}')
    return seen


def build_core(ck, outdir, pipeline=None, build_id=None):
    """Emit dwn_core.v + dwn_core_params.vh, then read them back and check.

    Replaces the study's argparse `main()`. Returns a dict the caller can report from --
    nothing is printed here, because a library that prints is a library you cannot call twice.

    Raises EmitterMismatch if the read-back disagrees with the checkpoint. That is deliberate:
    an emitter that half-succeeded should not leave a file on disk anyone might synthesize --
    and it is an exception rather than an `assert` because `python -O` deletes asserts, which
    made this promise false under a flag nobody thinks about (phase8-ledger.md §4).
    """
    from .config import Pipeline
    pipeline = pipeline or Pipeline()

    out_path = os.path.join(outdir, 'dwn_core.v')
    layers, input_bits, group, score_w, core_latency = emit(
        ck, out_path, pipeline.lut, pipeline.pop, pipeline.out, build_id=build_id)

    total = sum(t.shape[0] for t, _, _ in layers)
    seen = verify_emitted(out_path, layers, ck['config']['n'])

    return {
        'path': out_path,
        # The extracted (tables, wiring, kind) per layer, handed back rather than re-derived by
        # the caller. vectors.generate() labels its vectors with these SAME arrays, so the
        # testbench and the RTL cannot be built from different readings of the checkpoint --
        # which is the one invariant in CLAUDE.md that turns a green testbench into a lie.
        # Re-extracting would be deterministic and would almost always agree; "almost" is the
        # problem.
        'layers_extracted': layers,
        'nodes': total,
        'nodes_checked': seen,
        'layers': len(layers),
        'input_bits': input_bits,
        'group': group,
        'score_bits': score_w,
        'core_latency': core_latency,
    }
