"""Emit the model-specific DWN core Verilog from a checkpoint, then read it back and check it.

What is hand-written vs emitted:
  hand-written   rtl/lut_node.v, rtl/popcount.v, rtl/argmax.v -- shipped as package data. The
                 structure and the address/tie-break conventions, i.e. everything with a
                 decision in it
  emitted        dwn_core.v -- one truth table and n wire indices per node, i.e. everything
                 that is pure transcription

⚠️ `verify_emitted()` below is NOT the gate. It parses the emitted file back and asserts every
table and wire index against the checkpoint, which catches a wrong constant and -- the reason
it exists -- a reversed address concatenation. But it only proves the file SAYS what the
checkpoint says. It says nothing about how the Verilog BEHAVES. In the study repo an emitter's
own read-back reported 20/20 correct while the design was wrong on 958 of 1,504 vectors. Only
a simulator closes that gap. See CLAUDE.md, "the gate".

Ported from the study repo's `rtlgen/emit_core.py`. Changes: the CLI `main()` became
`build_core()`, and imports are package-relative.
"""

import os
import re

import numpy as np

from .extract import layer_indices, extract_tables, extract_wiring

# DEFAULT pipeline depth. `emit()` takes the depths as arguments so a build can vary them
# without editing this file. config.py carries the chosen values; these three are only the
# fallback for a caller that says nothing.
PIPE_LUT = 1
PIPE_POP = 1
PIPE_OUT = 1


def table_to_hex(row):
    """bool[2**n] -> integer where bit `addr` is row[addr].

    Written as an explicit loop, not np.packbits. packbits pads a partial byte on the LOW side
    with bitorder='big', so a table shorter than 8 entries came out shifted left: at n=2 the
    4-entry table [1,1,1,0] emitted as 0x70 instead of 0x07 and every entry sat at the wrong
    address. n>=3 was unaffected (2**n is then a whole number of bytes), which is why n=6 never
    showed it.

    That mattered more than a normal off-by-one: small n is exactly where a design is also
    expected to fail for unrelated reasons (routing congestion), so a gate failure caused by
    this bug would have been indistinguishable from an expected hardware limit.

    n <= 6, so at most 64 iterations per node -- clarity beats vectorization here.
    """
    v = 0
    for addr, bit in enumerate(row):
        if bit:
            v |= 1 << addr
    return v


MAX_N = 6      # one LUT6 holds 2**6 entries; see the assertion in emit()


def emit(ck, out_path, pipe_lut=PIPE_LUT, pipe_pop=PIPE_POP, pipe_out=PIPE_OUT):
    cfg = ck['config']
    n, num_classes = cfg['n'], cfg['num_classes']

    # n > 6 would emit a 2**n-bit table into a 64-bit parameter and Verilog would TRUNCATE it
    # silently -- the design elaborates, synthesizes, and computes garbage for every address
    # above 63. Same shape as the n=2 packing bug: valid-looking, totally wrong.
    #
    # Supporting n=8 is not just a width change. Three things move together (this format string,
    # `parameter [63:0] TABLE` in rtl/lut_node.v, and verify_emitted's `64'h([0-9A-F]{16})`
    # regex) -- but more importantly one node would no longer BE one LUT6, which is the
    # architectural premise the whole approach rests on. A different tool, not a wider parameter.
    assert n <= MAX_N, (
        f'n={n} exceeds MAX_N={MAX_N}. A {2**n}-entry table does not fit the 64-bit TABLE '
        f'parameter and would be silently truncated. Supporting it requires changing '
        f'rtl/lut_node.v, this emitter and verify_emitted together -- and one node would no '
        f'longer map to one LUT6, which is the premise the whole approach rests on.')
    sd = ck['state_dict']

    layers = []
    for i in layer_indices(sd):
        layers.append((extract_tables(sd, i), *extract_wiring(sd, i, n)))

    # The encoder's output width, read from the thresholds themselves -- (features, z), so
    # .size is features x z. NEVER a literal feature count -- in the study repo this was once
    # `16 * z`, one dataset's feature count written in, and it did not fail loudly: it emits a
    # core whose input port is the wrong width, which elaborates and then disagrees with the
    # encoder. emit_encoder.py derives it the same way, from the same array.
    input_bits = ck['thermometer']['thresholds'].numpy().size
    final_width = layers[-1][0].shape[0]
    group = final_width // num_classes
    score_w = int(np.ceil(np.log2(group + 1)))
    idx_w = max(1, int(np.ceil(np.log2(num_classes))))

    L = []
    L.append('// GENERATED by dwn2rtl -- do not edit by hand.')
    L.append(f"// run        : {ck.get('run_name', '(unnamed)')}")
    L.append(f"// config     : n={n}, layers={cfg['layers']}, z={cfg['thermometer_bits']}, "
             f'classes={num_classes}')
    L.append(f"// accuracy   : final {ck['results']['final_acc']:.4f} "
             f"(software, {ck['results']['best_acc']:.4f} best epoch)")
    L.append('//')
    L.append('// Takes the FULL binarized vector, so it can be driven straight from the')
    L.append('// core-level test vectors. Typically most of those bits feed no node at all and')
    L.append('// synthesis is expected to drop them; dwn_top drives only the bits that matter,')
    L.append('// from the thermometer encoder.')
    L.append('')
    # Required: xsim rejects a design mixing modules with and without a timescale, and the
    # testbench declares one.
    L.append('`timescale 1ns / 1ps')
    L.append('`default_nettype none')
    L.append('')
    L.append('// Pipeline stages are parameters, not hand-placement, so depth can be swept')
    L.append('// without regenerating. Set any to 0 to compile that register out. LATENCY is the')
    L.append('// sum of the enabled stages and is emitted into dwn_core_params.vh for the')
    L.append('// testbench, so the two can never disagree about it.')
    L.append('//')
    L.append('// Placement follows measurement, not intuition: out-of-context synthesis put')
    L.append('// 10.194 ns in this module against 2.962 ns in the encoder, so the depth is in')
    L.append('// the popcount and argmax trees. Hence a stage after each of them.')
    L.append('module dwn_core #(')
    L.append(f'    parameter integer PIPE_LUT = {pipe_lut},   // after each LUT layer')
    L.append(f'    parameter integer PIPE_POP = {pipe_pop},   // after the popcounts')
    L.append(f'    parameter integer PIPE_OUT = {pipe_out}    // after the argmax')
    L.append(')(')
    L.append('    input  wire clk,')
    L.append(f'    input  wire [{input_bits-1}:0] x,')
    L.append(f'    output wire [{idx_w-1}:0]    class_idx')
    L.append(');')
    L.append('')

    prev = 'x'
    for li, (tables, wiring, kind) in enumerate(layers):
        count = tables.shape[0]
        L.append(f'    // ---- layer {li}: {count} nodes, {kind} mapping ----')
        L.append(f'    wire [{count-1}:0] layer{li};')
        for j in range(count):
            # Concatenation is MSB-first, and slot 0 must land on addr[0], so the slots are
            # listed in REVERSE order here. This is the single most reversible-looking
            # decision in the whole design (docs/checkpoint-format.md §2).
            slots = ', '.join(f'{prev}[{b}]' for b in reversed(wiring[j].tolist()))
            L.append(f'    lut_node #(.N({n}), .TABLE(64\'h{table_to_hex(tables[j]):016X}))')
            L.append(f'        u_l{li}_n{j} (.addr({{{slots}}}), .out(layer{li}[{j}]));')
        L.append('')
        L.append(f'    wire [{count-1}:0] layer{li}_q;')
        L.append(f'    pipe_reg #(.WIDTH({count}), .ENABLE(PIPE_LUT)) u_pipe_l{li} '
                 f'(.clk(clk), .d(layer{li}), .q(layer{li}_q));')
        L.append('')
        prev = f'layer{li}_q'

    L.append('    // ---- output stage: contiguous per-class popcounts, then argmax ----')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores;')
    for c in range(num_classes):
        lo, hi = c * group, (c + 1) * group - 1
        L.append(f'    popcount #(.WIDTH({group})) u_pc{c} '
                 f'(.bits({prev}[{hi}:{lo}]), .count(scores[{c*score_w+score_w-1}:{c*score_w}]));')
    L.append('')
    L.append(f'    wire [{num_classes*score_w-1}:0] scores_q;')
    L.append(f'    pipe_reg #(.WIDTH({num_classes*score_w}), .ENABLE(PIPE_POP)) u_pipe_pop '
             f'(.clk(clk), .d(scores), .q(scores_q));')
    L.append('')
    L.append(f'    wire [{idx_w-1}:0] idx;')
    L.append(f'    argmax #(.K({num_classes}), .W({score_w})) u_argmax '
             f'(.scores_flat(scores_q), .index(idx));')
    L.append('')
    L.append(f'    pipe_reg #(.WIDTH({idx_w}), .ENABLE(PIPE_OUT)) u_pipe_out '
             f'(.clk(clk), .d(idx), .q(class_idx));')
    L.append('')
    L.append('endmodule')
    L.append('')
    L.append('`default_nettype wire')

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, 'w') as f:
        f.write('\n'.join(L) + '\n')

    # Latency emitted alongside the RTL so the testbench reads it from the same source that
    # generated the pipeline. Hardcoding it in the testbench is how a depth change silently
    # turns into an off-by-one comparison against the wrong vector.
    core_latency = pipe_lut * len(layers) + pipe_pop + pipe_out
    # The individual stage enables go here too, not just their sum. dwn_top instantiates
    # dwn_core with .PIPE_LUT(PIPE_LUT) etc., so dwn_top's OWN defaults override the core's --
    # emitting a 0 here and leaving dwn_top at 1 would silently put the stage back. Publishing
    # them makes emit_encoder read the depth rather than be told it a second time.
    with open(os.path.join(os.path.dirname(out_path), 'dwn_core_params.vh'), 'w') as f:
        f.write('// GENERATED by dwn2rtl -- do not edit.\n')
        f.write(f'`define DWN_CORE_LATENCY {core_latency}\n')
        f.write(f'`define DWN_CORE_PIPE_LUT {pipe_lut}\n')
        f.write(f'`define DWN_CORE_PIPE_POP {pipe_pop}\n')
        f.write(f'`define DWN_CORE_PIPE_OUT {pipe_out}\n')

    return layers, input_bits, group, score_w, core_latency


def verify_emitted(path, layers, n):
    """Parse the emitted Verilog back and check it against the checkpoint.

    Catches a wrong table, a wrong wire index, and -- most importantly -- a reversed address
    concatenation. Cheap, and it fails at emit time rather than in simulation.

    ⚠️ NOT a substitute for the simulator. It proves the file says what the checkpoint says,
    which is a claim about transcription, not about behaviour. See the module docstring.
    """
    src = open(path).read()
    pat = re.compile(
        r"lut_node #\(\.N\(\d+\), \.TABLE\(64'h([0-9A-F]{16})\)\)\s*"
        r"u_l(\d+)_n(\d+) \(\.addr\(\{([^}]*)\}\)",
        re.MULTILINE)

    seen = 0
    for m in pat.finditer(src):
        tbl_hex, li, j = m.group(1), int(m.group(2)), int(m.group(3))
        tables, wiring, _ = layers[li]

        expect_hex = f'{table_to_hex(tables[j]):016X}'
        assert tbl_hex == expect_hex, (
            f'layer {li} node {j}: table {tbl_hex} != expected {expect_hex}')

        idx = [int(x) for x in re.findall(r'\[(\d+)\]', m.group(4))]
        # emitted MSB-first, so reversing recovers slot order (slot 0 first)
        assert idx[::-1] == wiring[j].tolist(), (
            f'layer {li} node {j}: wiring {idx[::-1]} != expected {wiring[j].tolist()} '
            '-- address bit order is wrong')
        seen += 1

    total = sum(t.shape[0] for t, _, _ in layers)
    assert seen == total, f'parsed {seen} nodes, expected {total}'
    return seen


def build_core(ck, outdir, pipeline=None):
    """Emit dwn_core.v + dwn_core_params.vh, then read them back and check.

    Replaces the study repo's argparse `main()`. Returns a dict the caller can report from --
    nothing is printed here, because a library that prints is a library you cannot call twice.

    Raises AssertionError if the read-back disagrees with the checkpoint. That is deliberate:
    an emitter that half-succeeded should not leave a file on disk anyone might synthesize.
    """
    from .config import Pipeline
    pipeline = pipeline or Pipeline()

    out_path = os.path.join(outdir, 'dwn_core.v')
    layers, input_bits, group, score_w, core_latency = emit(
        ck, out_path, pipeline.lut, pipeline.pop, pipeline.out)

    total = sum(t.shape[0] for t, _, _ in layers)
    seen = verify_emitted(out_path, layers, ck['config']['n'])

    return {
        'path': out_path,
        'nodes': total,
        'nodes_checked': seen,
        'layers': len(layers),
        'input_bits': input_bits,
        'group': group,
        'score_bits': score_w,
        'core_latency': core_latency,
    }
